### ISSUE TITLE
Syllabe won't break for 'အကြောင်း'

### ISSUE THREAD

**Issue by khzaw** [thantthet/MyanmarParser-Py#1]
Hi, just want to report that script is not breaking down syllables for cases like 'အကြောင်း', 'အကြံ'. Haven't really looked into the source code myself, but I am happy to send a PR if I have done so.

**Comment by thantthet** [comment]
syllables that begins with အ+.... should be counted as single syllable. So,
i think it is breaking correctly.

**Comment by khzaw** [comment]
@thantthet Ah, I see. Thanks for the clarification. I will close the issue.
